# Generated by Django 3.1.6 on 2025-05-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20250414_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Consultation with a Cardiologist', 'Consultation with a Cardiologist'), ('Cardiac Diagnostic Testing', 'Cardiac Diagnostic Testing'), ('Stress Testing', 'Stress Testing'), ('Cardiac Imaging', 'Cardiac Imaging'), ('Cardiac Rehabilitation Program', 'Cardiac Rehabilitation Program')], default='Consultation with a Cardiologis', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.CharField(choices=[('9 AM', '9 AM'), ('10 AM', '10 AM'), ('11 AM', '11 AM'), ('12 PM', '12 PM'), ('1 PM', '1 PM'), ('2 PM', '2 PM'), ('3 PM', '3 PM'), ('4 PM', '4 PM'), ('5 PM', '5 PM'), ('6 PM', '6 PM'), ('7 PM', '7 PM')], default='9 PM', max_length=10),
        ),
    ]
