# Generated by Django 3.1.6 on 2025-05-11 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20250511_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.CharField(choices=[('Consultation with a Cardiologist', 'Consultation with a Cardiologist'), ('Cardiac Diagnostic Testing', 'Cardiac Diagnostic Testing'), ('Stress Testing', 'Stress Testing'), ('Cardiac Imaging', 'Cardiac Imaging'), ('Cardiac Rehabilitation Program', 'Cardiac Rehabilitation Program')], default='Consultation with a Cardiologist', max_length=50),
        ),
    ]
