# Generated by Django 3.1.6 on 2025-07-30 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hms', '0002_bill'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bill',
        ),
    ]
